language: python

dist: xenial

python:
  - "3.7"

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

script:
  - "make"
  - "make test"

notifications:
  email:
    on_success: never
    on_failure: always